"use client"

import type React from "react"
import { createContext, useState, useContext, useEffect } from "react"

// Define supported languages
export type Language = {
  code: string
  name: string
  nativeName: string
  direction: "ltr" | "rtl"
}

export const languages: Language[] = [
  { code: "en", name: "English", nativeName: "English", direction: "ltr" },
  { code: "es", name: "Spanish", nativeName: "Español", direction: "ltr" },
  { code: "fr", name: "French", nativeName: "Français", direction: "ltr" },
  { code: "de", name: "German", nativeName: "Deutsch", direction: "ltr" },
  { code: "zh", name: "Chinese", nativeName: "中文", direction: "ltr" },
  { code: "ja", name: "Japanese", nativeName: "日本語", direction: "ltr" },
  { code: "ar", name: "Arabic", nativeName: "العربية", direction: "rtl" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", direction: "ltr" },
  { code: "ru", name: "Russian", nativeName: "Русский", direction: "ltr" },
  { code: "pt", name: "Portuguese", nativeName: "Português", direction: "ltr" },
  { code: "it", name: "Italian", nativeName: "Italiano", direction: "ltr" },
  { code: "ko", name: "Korean", nativeName: "한국어", direction: "ltr" },
]

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(languages[0])

  useEffect(() => {
    const savedLang = localStorage.getItem("language")
    if (savedLang) {
      const lang = languages.find((l) => l.code === savedLang)
      if (lang) {
        setLanguageState(lang)
      }
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang.code)
    document.documentElement.dir = lang.direction
    document.documentElement.lang = lang.code
  }

  const t = (key: string): string => {
    const keys = key.split(".") ;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let value: any = translations

    for (const k of keys) {
      if (value && value[k]) {
        value = value[k]
      } else {
        return key // Return the key if translation not found
      }
    }

    if (typeof value === "string") {
      return value
    }

    if (value && value[language.code]) {
      return value[language.code]
    }

    // Fallback to English
    if (value && value["en"]) {
      return value["en"]
    }

    return key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

// Translations for the entire website
const translations = {
  header: {
    about: {
      en: "About",
      es: "Sobre mí",
      fr: "À propos",
      de: "Über mich",
      zh: "关于",
      ja: "について",
      ar: "حول",
      hi: "परिचय",
      ru: "Обо мне",
      pt: "Sobre",
      it: "Chi sono",
      ko: "소개",
    },
    skills: {
      en: "Skills",
      es: "Habilidades",
      fr: "Compétences",
      de: "Fähigkeiten",
      zh: "技能",
      ja: "スキル",
      ar: "المهارات",
      hi: "कौशल",
      ru: "Навыки",
      pt: "Habilidades",
      it: "Competenze",
      ko: "기술",
    },
    experience: {
      en: "Experience",
      es: "Experiencia",
      fr: "Expérience",
      de: "Erfahrung",
      zh: "经验",
      ja: "経験",
      ar: "الخبرة",
      hi: "अनुभव",
      ru: "Опыт",
      pt: "Experiência",
      it: "Esperienza",
      ko: "경력",
    },
    projects: {
      en: "Projects",
      es: "Proyectos",
      fr: "Projets",
      de: "Projekte",
      zh: "项目",
      ja: "プロジェクト",
      ar: "المشاريع",
      hi: "परियोजनाएँ",
      ru: "Проекты",
      pt: "Projetos",
      it: "Progetti",
      ko: "프로젝트",
    },
    contact: {
      en: "Contact",
      es: "Contacto",
      fr: "Contact",
      de: "Kontakt",
      zh: "联系",
      ja: "連絡先",
      ar: "اتصل",
      hi: "संपर्क",
      ru: "Контакты",
      pt: "Contato",
      it: "Contatti",
      ko: "연락처",
    },
  },
  hero: {
    title: {
      en: "Amit Kumar",
      es: "Amit Kumar",
      fr: "Amit Kumar",
      de: "Amit Kumar",
      zh: "Amit Kumar",
      ja: "Amit Kumar",
      ar: "أميت كومار",
      hi: "अमित कुमार",
      ru: "Амит Кумар",
      pt: "Amit Kumar",
      it: "Amit Kumar",
      ko: "아밋 쿠마르",
    },
    subtitle: {
      en: "Full Stack Developer | React.js Specialist | Node.js Expert",
      es: "Desarrollador Full Stack | Especialista en React.js | Experto en Node.js",
      fr: "Développeur Full Stack | Spécialiste React.js | Expert Node.js",
      de: "Full-Stack-Entwickler | React.js-Spezialist | Node.js-Experte",
      zh: "全栈开发者 | React.js 专家 | Node.js 专家",
      ja: "フルスタック開発者 | React.js スペシャリスト | Node.js エキスパート",
      ar: "مطور الويب الشامل | متخصص في React.js | خبير في Node.js",
      hi: "फुल स्टैक डेवलपर | React.js विशेषज्ञ | Node.js विशेषज्ञ",
      ru: "Full Stack Разработчик | Специалист по React.js | Эксперт Node.js",
      pt: "Desenvolvedor Full Stack | Especialista em React.js | Especialista em Node.js",
      it: "Sviluppatore Full Stack | Specialista React.js | Esperto Node.js",
      ko: "풀스택 개발자 | React.js 전문가 | Node.js 전문가",
    },
    getInTouch: {
      en: "Get in Touch",
      es: "Contáctame",
      fr: "Me contacter",
      de: "Kontaktieren",
      zh: "联系我",
      ja: "お問い合わせ",
      ar: "تواصل معي",
      hi: "संपर्क करें",
      ru: "Связаться",
      pt: "Entre em contato",
      it: "Contattami",
      ko: "연락하기",
    },
    viewCV: {
      en: "View CV",
      es: "Ver CV",
      fr: "Voir CV",
      de: "Lebenslauf",
      zh: "查看简历",
      ja: "履歴書を見る",
      ar: "عرض السيرة الذاتية",
      hi: "सीवी देखें",
      ru: "Посмотреть резюме",
      pt: "Ver currículo",
      it: "Vedi CV",
      ko: "이력서 보기",
    },
    downloadCV: {
      en: "Download CV",
      es: "Descargar CV",
      fr: "Télécharger CV",
      de: "Lebenslauf herunterladen",
      zh: "下载简历",
      ja: "履歴書をダウンロード",
      ar: "تحميل السيرة الذاتية",
      hi: "सीवी डाउनलोड करें",
      ru: "Скачать резюме",
      pt: "Baixar currículo",
      it: "Scarica CV",
      ko: "이력서 다운로드",
    },
  },
  about: {
    title: {
      en: "About Me",
      es: "Sobre Mí",
      fr: "À Propos de Moi",
      de: "Über Mich",
      zh: "关于我",
      ja: "私について",
      ar: "نبذة عني",
      hi: "मेरे बारे में",
      ru: "Обо мне",
      pt: "Sobre Mim",
      it: "Su di Me",
      ko: "나에 대해",
    },
    description: {
      en: "A proficient Full Stack Developer with 3+ years of experience in both front-end and back-end development. I specialize in developing user-centric applications and leading projects from conception to deployment. My expertise lies in collaborative teamwork and leveraging innovative technologies to achieve project excellence. I'm passionate about delivering efficient, maintainable code for long-term use and continuously improving my skills in the ever-evolving tech landscape.",
      es: "Un desarrollador Full Stack competente con más de 3 años de experiencia en desarrollo front-end y back-end. Me especializo en desarrollar aplicaciones centradas en el usuario y liderar proyectos desde la concepción hasta la implementación. Mi experiencia radica en el trabajo en equipo colaborativo y el aprovechamiento de tecnologías innovadoras para lograr la excelencia del proyecto. Me apasiona entregar código eficiente y mantenible para uso a largo plazo y mejorar continuamente mis habilidades en el panorama tecnológico en constante evolución.",
      fr: "Un développeur Full Stack compétent avec plus de 3 ans d'expérience en développement front-end et back-end. Je me spécialise dans le développement d'applications centrées sur l'utilisateur et la direction de projets de la conception au déploiement. Mon expertise réside dans le travail d'équipe collaboratif et l'utilisation de technologies innovantes pour atteindre l'excellence du projet. Je suis passionné par la fourniture de code efficace et maintenable pour une utilisation à long terme et l'amélioration continue de mes compétences dans le paysage technologique en constante évolution.",
      de: "Ein kompetenter Full-Stack-Entwickler mit mehr als 3 Jahren Erfahrung in der Front-End- und Back-End-Entwicklung. Ich bin spezialisiert auf die Entwicklung benutzerzentrierter Anwendungen und die Leitung von Projekten von der Konzeption bis zur Bereitstellung. Meine Expertise liegt in der kollaborativen Teamarbeit und dem Einsatz innovativer Technologien, um Projektexzellenz zu erreichen. Ich bin leidenschaftlich daran interessiert, effizienten, wartbaren Code für die langfristige Nutzung zu liefern und meine Fähigkeiten in der sich ständig weiterentwickelnden Technologielandschaft kontinuierlich zu verbessern.",
      zh: "一位精通全栈开发的开发者，拥有3年以上的前端和后端开发经验。我专注于开发以用户为中心的应用程序，并从概念到部署领导项目。我的专长在于协作团队合作和利用创新技术实现项目卓越。我热衷于提供高效、可维护的代码用于长期使用，并在不断发展的技术领域中持续提升我的技能。",
      ja: "フロントエンドとバックエンドの開発において3年以上の経験を持つ熟練したフルスタック開発者です。ユーザー中心のアプリケーションの開発と、構想から展開までのプロジェクトのリードを専門としています。私の専門知識は、協力的なチームワークと革新的な技術を活用してプロジェクトの卓越性を達成することにあります。長期的な使用のための効率的で保守可能なコードの提供と、常に進化するテクノロジーの風景の中でスキルを継続的に向上させることに情熱を持っています。",
      ar: "مطور ويب شامل متمرس مع أكثر من 3 سنوات من الخبرة في تطوير الواجهة الأمامية والخلفية. أتخصص في تطوير التطبيقات التي تركز على المستخدم وقيادة المشاريع من التصور إلى النشر. تكمن خبرتي في العمل الجماعي التعاوني والاستفادة من التقنيات المبتكرة لتحقيق التميز في المشروع. أنا شغوف بتقديم كود فعال وقابل للصيانة للاستخدام على المدى الطويل وتحسين مهاراتي باستمرار في مشهد التكنولوجيا المتطور باستمرار.",
      hi: "एक कुशल फुल स्टैक डेवलपर जिसे फ्रंट-एंड और बैक-एंड विकास में 3+ वर्षों का अनुभव है। मैं उपयोगकर्ता-केंद्रित अनुप्रयोगों को विकसित करने और अवधारणा से परिनियोजन तक परियोजनाओं का नेतृत्व करने में विशेषज्ञता रखता हूं। मेरी विशेषज्ञता सहयोगी टीमवर्क और परियोजना उत्कृष्टता प्राप्त करने के लिए नवीन प्रौद्योगिकियों का लाभ उठाने में है। मैं दीर्घकालिक उपयोग के लिए कुशल, रखरखाव योग्य कोड प्रदान करने और लगातार विकसित हो रहे तकनीकी परिदृश्य में अपने कौशल को निरंतर सुधारने के लिए उत्साहित हूं।",
      ru: "Опытный Full Stack разработчик с более чем 3-летним опытом работы в области фронтенд и бэкенд разработки. Я специализируюсь на разработке пользовательских приложений и руководстве проектами от концепции до развертывания. Моя экспертиза заключается в совместной командной работе и использовании инновационных технологий для достижения проектного совершенства. Я увлечен предоставлением эффективного, поддерживаемого кода для долгосрочного использования и постоянным совершенствованием своих навыков в постоянно развивающемся технологическом ландшафте.",
      pt: "Um desenvolvedor Full Stack proficiente com mais de 3 anos de experiência em desenvolvimento front-end e back-end. Eu me especializo em desenvolver aplicativos centrados no usuário e liderar projetos desde a concepção até a implantação. Minha experiência está no trabalho em equipe colaborativo e no aproveitamento de tecnologias inovadoras para alcançar a excelência do projeto. Sou apaixonado por entregar código eficiente e sustentável para uso a longo prazo e melhorar continuamente minhas habilidades no cenário tecnológico em constante evolução.",
      it: "Uno sviluppatore Full Stack competente con oltre 3 anni di esperienza nello sviluppo front-end e back-end. Mi specializzo nello sviluppo di applicazioni incentrate sull'utente e nella guida di progetti dalla concezione alla distribuzione. La mia competenza risiede nel lavoro di squadra collaborativo e nello sfruttamento di tecnologie innovative per raggiungere l'eccellenza del progetto. Sono appassionato di fornire codice efficiente e manutenibile per l'uso a lungo termine e di migliorare continuamente le mie competenze nel panorama tecnologico in continua evoluzione.",
      ko: "프론트엔드 및 백엔드 개발 분야에서 3년 이상의 경험을 가진 숙련된 풀스택 개발자입니다. 사용자 중심 애플리케이션 개발 및 개념에서 배포까지 프로젝트를 이끄는 데 전문화되어 있습니다. 저의 전문성은 협업 팀워크와 혁신적인 기술을 활용하여 프로젝트 우수성을 달성하는 데 있습니다. 장기적인 사용을 위한 효율적이고 유지 관리 가능한 코드를 제공하고 끊임없이 발전하는 기술 환경에서 지속적으로 기술을 향상시키는 데 열정을 가지고 있습니다.",
    },
  },
  skills: {
    title: {
      en: "Skills",
      es: "Habilidades",
      fr: "Compétences",
      de: "Fähigkeiten",
      zh: "技能",
      ja: "スキル",
      ar: "المهارات",
      hi: "कौशल",
      ru: "Навыки",
      pt: "Habilidades",
      it: "Competenze",
      ko: "기술",
    },
  },
  experience: {
    title: {
      en: "Work Experience",
      es: "Experiencia Laboral",
      fr: "Expérience Professionnelle",
      de: "Berufserfahrung",
      zh: "工作经验",
      ja: "職務経験",
      ar: "الخبرة العملية",
      hi: "कार्य अनुभव",
      ru: "Опыт работы",
      pt: "Experiência Profissional",
      it: "Esperienza Lavorativa",
      ko: "직장 경력",
    },
    projects: {
      en: "Projects",
      es: "Proyectos",
      fr: "Projets",
      de: "Projekte",
      zh: "项目",
      ja: "プロジェクト",
      ar: "المشاريع",
      hi: "परियोजनाएँ",
      ru: "Проекты",
      pt: "Projetos",
      it: "Progetti",
      ko: "프로젝트",
    },
    role: {
      en: "Role",
      es: "Rol",
      fr: "Rôle",
      de: "Rolle",
      zh: "角色",
      ja: "役割",
      ar: "الدور",
      hi: "भूमिका",
      ru: "Роль",
      pt: "Função",
      it: "Ruolo",
      ko: "역할",
    },
    techStack: {
      en: "Tech Stack",
      es: "Tecnologías",
      fr: "Stack Technique",
      de: "Tech-Stack",
      zh: "技术栈",
      ja: "技術スタック",
      ar: "التقنيات المستخدمة",
      hi: "तकनीकी स्टैक",
      ru: "Технологии",
      pt: "Stack Tecnológico",
      it: "Stack Tecnologico",
      ko: "기술 스택",
    },
    contributions: {
      en: "Contributions",
      es: "Contribuciones",
      fr: "Contributions",
      de: "Beiträge",
      zh: "贡献",
      ja: "貢献",
      ar: "المساهمات",
      hi: "योगदान",
      ru: "Вклад",
      pt: "Contribuições",
      it: "Contributi",
      ko: "기여",
    },
    keyContributions: {
      en: "Key Contributions",
      es: "Contribuciones Clave",
      fr: "Contributions Clés",
      de: "Hauptbeiträge",
      zh: "主要贡献",
      ja: "主な貢献",
      ar: "المساهمات الرئيسية",
      hi: "प्रमुख योगदान",
      ru: "Ключевой вклад",
      pt: "Contribuições Principais",
      it: "Contributi Chiave",
      ko: "주요 기여",
    },
    fullStackDeveloper: {
      en: "Full Stack Developer",
      es: "Desarrollador Full Stack",
      fr: "Développeur Full Stack",
      de: "Full-Stack-Entwickler",
      zh: "全栈开发工程师",
      ja: "フルスタック開発者",
      ar: "مطور الويب الشامل",
      hi: "फुल स्टैक डेवलपर",
      ru: "Full Stack Разработчик",
      pt: "Desenvolvedor Full Stack",
      it: "Sviluppatore Full Stack",
      ko: "풀스택 개발자",
    },
    nodeJsDeveloper: {
      en: "Node.js Developer (Internship)",
      es: "Desarrollador Node.js (Prácticas)",
      fr: "Développeur Node.js (Stage)",
      de: "Node.js-Entwickler (Praktikum)",
      zh: "Node.js 开发工程师（实习）",
      ja: "Node.js 開発者（インターンシップ）",
      ar: "مطور Node.js (تدريب)",
      hi: "Node.js डेवलपर (इंटर्नशिप)",
      ru: "Node.js Разработчик (Стажировка)",
      pt: "Desenvolvedor Node.js (Estágio)",
      it: "Sviluppatore Node.js (Tirocinio)",
      ko: "Node.js 개발자 (인턴십)",
    },
    kindlebit: {
      en: "Kindlebit Solution Pvt Ltd",
      es: "Kindlebit Solution Pvt Ltd",
      fr: "Kindlebit Solution Pvt Ltd",
      de: "Kindlebit Solution Pvt Ltd",
      zh: "Kindlebit Solution Pvt Ltd",
      ja: "Kindlebit Solution Pvt Ltd",
      ar: "Kindlebit Solution Pvt Ltd",
      hi: "Kindlebit Solution Pvt Ltd",
      ru: "Kindlebit Solution Pvt Ltd",
      pt: "Kindlebit Solution Pvt Ltd",
      it: "Kindlebit Solution Pvt Ltd",
      ko: "Kindlebit Solution Pvt Ltd",
    },
    avipl: {
      en: "AVIPL",
      es: "AVIPL",
      fr: "AVIPL",
      de: "AVIPL",
      zh: "AVIPL",
      ja: "AVIPL",
      ar: "AVIPL",
      hi: "AVIPL",
      ru: "AVIPL",
      pt: "AVIPL",
      it: "AVIPL",
      ko: "AVIPL",
    },
    kindlebitPeriod: {
      en: "January 2022 - Present",
      es: "Enero 2022 - Presente",
      fr: "Janvier 2022 - Présent",
      de: "Januar 2022 - Heute",
      zh: "2022年1月 - 至今",
      ja: "2022年1月 - 現在",
      ar: "يناير 2022 - الحاضر",
      hi: "जनवरी 2022 - वर्तमान",
      ru: "Январь 2022 - Настоящее время",
      pt: "Janeiro 2022 - Presente",
      it: "Gennaio 2022 - Presente",
      ko: "2022년 1월 - 현재",
    },
    aviplPeriod: {
      en: "August 2021 - November 2021",
      es: "Agosto 2021 - Noviembre 2021",
      fr: "Août 2021 - Novembre 2021",
      de: "August 2021 - November 2021",
      zh: "2021年8月 - 2021年11月",
      ja: "2021年8月 - 2021年11月",
      ar: "أغسطس 2021 - نوفمبر 2021",
      hi: "अगस्त 2021 - नवंबर 2021",
      ru: "Август 2021 - Ноябрь 2021",
      pt: "Agosto 2021 - Novembro 2021",
      it: "Agosto 2021 - Novembre 2021",
      ko: "2021년 8월 - 2021년 11월",
    },
    kindlebitDescription1: {
      en: "Developed responsive, scalable client applications, increasing user engagement by 30% and enhancing workflow efficiency.",
      es: "Desarrollé aplicaciones de cliente escalables y responsivas, aumentando la participación del usuario en un 30% y mejorando la eficiencia del flujo de trabajo.",
      fr: "Développé des applications client évolutives et réactives, augmentant l'engagement des utilisateurs de 30% et améliorant l'efficacité du flux de travail.",
      de: "Entwickelte responsive, skalierbare Client-Anwendungen, erhöhte das Nutzerengagement um 30% und verbesserte die Workflow-Effizienz.",
      zh: "开发了响应式、可扩展的客户端应用程序，将用户参与度提高了30%，并提高了工作流程效率。",
      ja: "レスポンシブでスケーラブルなクライアントアプリケーションを開発し、ユーザーエンゲージメントを30%向上させ、ワークフローの効率性を高めました。",
      ar: "طورت تطبيقات عميل متجاوبة وقابلة للتوسع، مما زاد من مشاركة المستخدم بنسبة 30٪ وعزز كفاءة سير العمل.",
      hi: "उत्तरदायी, स्केलेबल क्लाइंट एप्लिकेशन विकसित किए, जिससे उपयोगकर्ता जुड़ाव 30% बढ़ा और कार्यप्रवाह दक्षता बढ़ी।",
      ru: "Разработал отзывчивые, масштабируемые клиентские приложения, увеличив вовлеченность пользователей на 30% и повысив эффективность рабочего процесса.",
      pt: "Desenvolvi aplicativos de cliente responsivos e escaláveis, aumentando o engajamento do usuário em 30% e melhorando a eficiência do fluxo de trabalho.",
      it: "Ho sviluppato applicazioni client responsive e scalabili, aumentando il coinvolgimento degli utenti del 30% e migliorando l'efficienza del flusso di lavoro.",
      ko: "반응형, 확장 가능한 클라이언트 애플리케이션을 개발하여 사용자 참여도를 30% 증가시키고 워크플로 효율성을 향상시켰습니다.",
    },
    kindlebitDescription2: {
      en: "Collaborated with cross-functional teams to address user pain points and improve UX, ensuring smooth front-end and back-end integration.",
      es: "Colaboré con equipos multifuncionales para abordar los puntos débiles de los usuarios y mejorar la UX, garantizando una integración fluida entre el front-end y el back-end.",
      fr: "Collaboré avec des équipes interfonctionnelles pour résoudre les points de douleur des utilisateurs et améliorer l'UX, assurant une intégration fluide entre le front-end et le back-end.",
      de: "Zusammenarbeit mit funktionsübergreifenden Teams zur Behebung von Nutzerproblemen und Verbesserung der UX, wobei eine reibungslose Integration von Front-End und Back-End sichergestellt wurde.",
      zh: "与跨职能团队合作解决用户痛点并改善用户体验，确保前端和后端的顺畅集成。",
      ja: "ユーザーの課題に対処しUXを改善するために、クロスファンクショナルチームと協力し、フロントエンドとバックエンドのスムーズな統合を確保しました。",
      ar: "تعاونت مع فرق متعددة الوظائف لمعالجة نقاط الألم لدى المستخدمين وتحسين تجربة المستخدم، مما يضمن تكاملًا سلسًا بين الواجهة الأمامية والخلفية.",
      hi: "उपयोगकर्ता की समस्याओं को हल करने और UX को बेहतर बनाने के लिए क्रॉस-फंक्शनल टीमों के साथ सहयोग किया, जिससे फ्रंट-एंड और बैक-एंड एकीकरण सुचारू हुआ।",
      ru: "Сотрудничал с кросс-функциональными командами для решения проблемных точек пользователей и улучшения UX, обеспечивая плавную интеграцию фронтенда и бэкенда.",
      pt: "Colaborei com equipes multifuncionais para resolver pontos problemáticos dos usuários e melhorar a UX, garantindo uma integração suave entre front-end e back-end.",
      it: "Ho collaborato con team interfunzionali per affrontare i punti critici degli utenti e migliorare l'UX, garantendo un'integrazione fluida tra front-end e back-end.",
      ko: "사용자 문제점을 해결하고 UX를 개선하기 위해 다기능 팀과 협력하여 프론트엔드와 백엔드의 원활한 통합을 보장했습니다.",
    },
    kindlebitDescription3: {
      en: "Led projects from design through deployment, reviewing code for quality and scalability, and mentoring junior developers in best practices.",
      es: "Dirigí proyectos desde el diseño hasta la implementación, revisando el código para garantizar calidad y escalabilidad, y mentorizando a desarrolladores junior en mejores prácticas.",
      fr: "Dirigé des projets de la conception au déploiement, en examinant le code pour la qualité et l'évolutivité, et en encadrant les développeurs juniors dans les meilleures pratiques.",
      de: "Leitete Projekte vom Design bis zur Bereitstellung, überprüfte Code auf Qualität und Skalierbarkeit und mentorierte Junior-Entwickler in Best Practices.",
      zh: "从设计到部署领导项目，审查代码以确保质量和可扩展性，并指导初级开发人员采用最佳实践。",
      ja: "設計から展開までのプロジェクトを主導し、品質とスケーラビリティのためにコードをレビューし、ジュニア開発者にベストプラクティスを指導しました。",
      ar: "قدت المشاريع من التصميم إلى النشر، ومراجعة الكود للجودة وقابلية التوسع، وتوجيه المطورين المبتدئين في أفضل الممارسات.",
      hi: "डिज़ाइन से लेकर डिप्लॉयमेंट तक परियोजनाओं का नेतृत्व किया, गुणवत्ता और स्केलेबिलिटी के लिए कोड की समीक्षा की, और जूनियर डेवलपर्स को सर्वोत्तम प्रथाओं में मेंटर किया।",
      ru: "Руководил проектами от дизайна до развертывания, проверял код на качество и масштабируемость, и наставлял младших разработчиков в лучших практиках.",
      pt: "Liderei projetos desde o design até a implantação, revisando código para qualidade e escalabilidade, e orientando desenvolvedores juniores nas melhores práticas.",
      it: "Ho guidato progetti dalla progettazione alla distribuzione, revisionando il codice per qualità e scalabilità, e mentorando sviluppatori junior nelle migliori pratiche.",
      ko: "설계부터 배포까지 프로젝트를 이끌었으며, 품질과 확장성을 위한 코드 검토 및 주니어 개발자에게 모범 사례를 멘토링했습니다.",
    },
    kindlebitDescription4: {
      en: "Improved application performance through code optimization, reducing load times by 25% and implementing secure data handling practices.",
      es: "Mejoré el rendimiento de la aplicación mediante la optimización del código, reduciendo los tiempos de carga en un 25% e implementando prácticas seguras de manejo de datos.",
      fr: "Amélioré les performances des applications grâce à l'optimisation du code, réduisant les temps de chargement de 25% et mettant en œuvre des pratiques sécurisées de traitement des données.",
      de: "Verbesserte die Anwendungsleistung durch Code-Optimierung, reduzierte Ladezeiten um 25% und implementierte sichere Datenverarbeitungspraktiken.",
      zh: "通过代码优化改进应用程序性能，将加载时间减少25%，并实施安全的数据处理实践。",
      ja: "コード最適化によりアプリケーションのパフォーマンスを向上させ、ロード時間を25%削減し、安全なデータ処理プラクティスを実装しました。",
      ar: "حسنت أداء التطبيق من خلال تحسين الكود، مما قلل من أوقات التحميل بنسبة 25٪ وتنفيذ ممارسات آمنة لمعالجة البيانات.",
      hi: "कोड ऑप्टिमाइजेशन के माध्यम से एप्लिकेशन प्रदर्शन में सुधार किया, लोड टाइम को 25% कम किया और सुरक्षित डेटा हैंडलिंग प्रथाओं को लागू किया।",
      ru: "Улучшил производительность приложения путем оптимизации кода, сократив время загрузки на 25% и внедрив безопасные практики обработки данных.",
      pt: "Melhorei o desempenho do aplicativo por meio de otimização de código, reduzindo os tempos de carregamento em 25% e implementando práticas seguras de manipulação de dados.",
      it: "Ho migliorato le prestazioni dell'applicazione attraverso l'ottimizzazione del codice, riducendo i tempi di caricamento del 25% e implementando pratiche sicure di gestione dei dati.",
      ko: "코드 최적화를 통해 애플리케이션 성능을 향상시켜 로드 시간을 25% 줄이고 안전한 데이터 처리 관행을 구현했습니다.",
    },
    kindlebitDescription5: {
      en: "Integrated AI-powered solutions to enhance application intelligence and improve user experience.",
      es: "Integré soluciones impulsadas por IA para mejorar la inteligencia de la aplicación y mejorar la experiencia del usuario.",
      fr: "Intégré des solutions alimentées par l'IA pour améliorer l'intelligence des applications et améliorer l'expérience utilisateur.",
      de: "Integrierte KI-gestützte Lösungen zur Verbesserung der Anwendungsintelligenz und der Benutzererfahrung.",
      zh: "集成人工智能驱动的解决方案，以增强应用程序智能并改善用户体验。",
      ja: "AIを活用したソリューションを統合し、アプリケーションのインテリジェンスを強化し、ユーザーエクスペリエンスを向上させました。",
      ar: "دمجت حلول مدعومة بالذكاء الاصطناعي لتعزيز ذكاء التطبيق وتحسين تجربة المستخدم.",
      hi: "एप्लिकेशन इंटेलिजेंस को बढ़ाने और उपयोगकर्ता अनुभव को बेहतर बनाने के लिए AI-संचालित समाधानों को एकीकृत किया।",
      ru: "Интегрировал решения на базе ИИ для повышения интеллекта приложений и улучшения пользовательского опыта.",
      pt: "Integrei soluções alimentadas por IA para aprimorar a inteligência do aplicativo e melhorar a experiência do usuário.",
      it: "Ho integrato soluzioni basate sull'IA per migliorare l'intelligenza dell'applicazione e migliorare l'esperienza utente.",
      ko: "애플리케이션 지능을 향상시키고 사용자 경험을 개선하기 위해 AI 기반 솔루션을 통합했습니다.",
    },
    aviplDescription1: {
      en: "Developed secure and efficient APIs for e-commerce and educational platforms, enhancing functionality and user experience.",
      es: "Desarrollé APIs seguras y eficientes para plataformas de comercio electrónico y educativas, mejorando la funcionalidad y la experiencia del usuario.",
      fr: "Développé des API sécurisées et efficaces pour les plateformes de commerce électronique et éducatives, améliorant la fonctionnalité et l'expérience utilisateur.",
      de: "Entwickelte sichere und effiziente APIs für E-Commerce- und Bildungsplattformen, verbesserte Funktionalität und Benutzererfahrung.",
      zh: "为电子商务和教育平台开发安全高效的API，增强功能和用户体验。",
      ja: "eコマースおよび教育プラットフォーム向けの安全で効率的なAPIを開発し、機能性とユーザーエクスペリエンスを向上させました。",
      ar: "طورت واجهات برمجة تطبيقات آمنة وفعالة لمنصات التجارة الإلكترونية والتعليمية، مما عزز الوظائف وتجربة المستخدم.",
      hi: "ई-कॉमर्स और शैक्षिक प्लेटफॉर्म के लिए सुरक्षित और कुशल API विकसित की, जिससे कार्यक्षमता और उपयोगकर्ता अनुभव बढ़ा।",
      ru: "Разработал безопасные и эффективные API для платформ электронной коммерции и образования, улучшая функциональность и пользовательский опыт.",
      pt: "Desenvolvi APIs seguras e eficientes para plataformas de comércio eletrônico e educacionais, aprimorando a funcionalidade e a experiência do usuário.",
      it: "Ho sviluppato API sicure ed efficienti per piattaforme di e-commerce ed educative, migliorando la funzionalità e l'esperienza utente.",
      ko: "전자 상거래 및 교육 플랫폼을 위한 안전하고 효율적인 API를 개발하여 기능성과 사용자 경험을 향상시켰습니다.",
    },
    aviplDescription2: {
      en: "Implemented authentication and authorization features using JWT, improving application security.",
      es: "Implementé características de autenticación y autorización utilizando JWT, mejorando la seguridad de la aplicación.",
      fr: "Mis en œuvre des fonctionnalités d'authentification et d'autorisation à l'aide de JWT, améliorant la sécurité des applications.",
      de: "Implementierte Authentifizierungs- und Autorisierungsfunktionen mit JWT, verbesserte die Anwendungssicherheit.",
      zh: "使用JWT实现身份验证和授权功能，提高应用程序安全性。",
      ja: "JWTを使用して認証と認可の機能を実装し、アプリケーションのセキュリティを向上させました。",
      ar: "نفذت ميزات المصادقة والتفويض باستخدام JWT، مما حسن أمان التطبيق.",
      hi: "JWT का उपयोग करके प्रमाणीकरण और प्राधिकरण सुविधाओं को लागू किया, जिससे एप्लिकेशन सुरक्षा में सुधार हुआ।",
      ru: "Реализовал функции аутентификации и авторизации с использованием JWT, повысив безопасность приложения.",
      pt: "Implementei recursos de autenticação e autorização usando JWT, melhorando a segurança do aplicativo.",
      it: "Ho implementato funzionalità di autenticazione e autorizzazione utilizzando JWT, migliorando la sicurezza dell'applicazione.",
      ko: "JWT를 사용하여 인증 및 권한 부여 기능을 구현하여 애플리케이션 보안을 향상시켰습니다.",
    },
    aviplDescription3: {
      en: "Optimized database queries and API responses, reducing latency and improving overall system efficiency.",
      es: "Optimicé consultas de base de datos y respuestas de API, reduciendo la latencia y mejorando la eficiencia general del sistema.",
      fr: "Optimisé les requêtes de base de données et les réponses API, réduisant la latence et améliorant l'efficacité globale du système.",
      de: "Optimierte Datenbankabfragen und API-Antworten, reduzierte Latenz und verbesserte die Gesamteffizienz des Systems.",
      zh: "优化数据库查询和API响应，减少延迟并提高整体系统效率。",
      ja: "データベースクエリとAPIレスポンスを最適化し、レイテンシーを削減し、システム全体の効率性を向上させました。",
      ar: "حسنت استعلامات قاعدة البيانات واستجابات واجهة برمجة التطبيقات، مما قلل من زمن الاستجابة وحسن كفاءة النظام بشكل عام.",
      hi: "डेटाबेस क्वेरी और API प्रतिक्रियाओं को अनुकूलित किया, जिससे विलंबता कम हुई और समग्र सिस्टम दक्षता में सुधार हुआ।",
      ru: "Оптимизировал запросы к базе данных и ответы API, снизив задержку и повысив общую эффективность системы.",
      pt: "Otimizei consultas de banco de dados e respostas de API, reduzindo a latência e melhorando a eficiência geral do sistema.",
      it: "Ho ottimizzato le query del database e le risposte API, riducendo la latenza e migliorando l'efficienza complessiva del sistema.",
      ko: "데이터베이스 쿼리 및 API 응답을 최적화하여 지연 시간을 줄이고 전체 시스템 효율성을 향상시켰습니다.",
    },
    insiderHealth: {
      title: {
        en: "InsiderHealth AI",
        es: "InsiderHealth AI",
        fr: "InsiderHealth AI",
        de: "InsiderHealth AI",
        zh: "InsiderHealth AI",
        ja: "InsiderHealth AI",
        ar: "InsiderHealth AI",
        hi: "InsiderHealth AI",
        ru: "InsiderHealth AI",
        pt: "InsiderHealth AI",
        it: "InsiderHealth AI",
        ko: "InsiderHealth AI",
      },
      overview: {
        en: "An AI-powered health platform offering personalized health insights.",
        es: "Una plataforma de salud impulsada por IA que ofrece información personalizada sobre salud.",
        fr: "Une plateforme de santé alimentée par l'IA offrant des informations personnalisées sur la santé.",
        de: "Eine KI-gestützte Gesundheitsplattform, die personalisierte Gesundheitseinblicke bietet.",
        zh: "一个由人工智能驱动的健康平台，提供个性化的健康见解。",
        ja: "AIを活用した健康プラットフォームで、パーソナライズされた健康情報を提供します。",
        ar: "منصة صحية مدعومة بالذكاء الاصطناعي تقدم رؤى صحية مخصصة.",
        hi: "एक AI-संचालित स्वास्थ्य प्लेटफॉर्म जो व्यक्तिगत स्वास्थ्य अंतर्दृष्टि प्रदान करता है।",
        ru: "Платформа здоровья на базе ИИ, предлагающая персонализированные сведения о здоровье.",
        pt: "Uma plataforma de saúde alimentada por IA que oferece insights personalizados de saúde.",
        it: "Una piattaforma sanitaria basata sull'IA che offre approfondimenti sanitari personalizzati.",
        ko: "개인 맞춤형 건강 인사이트를 제공하는 AI 기반 건강 플랫폼입니다.",
      },
      techStack: {
        en: "Next.js (TypeScript), MySQL, AI models",
        es: "Next.js (TypeScript), MySQL, modelos de IA",
        fr: "Next.js (TypeScript), MySQL, modèles d'IA",
        de: "Next.js (TypeScript), MySQL, KI-Modelle",
        zh: "Next.js (TypeScript), MySQL, AI 模型",
        ja: "Next.js (TypeScript), MySQL, AIモデル",
        ar: "Next.js (TypeScript), MySQL, نماذج الذكاء الاصطناعي",
        hi: "Next.js (TypeScript), MySQL, AI मॉडल",
        ru: "Next.js (TypeScript), MySQL, модели ИИ",
        pt: "Next.js (TypeScript), MySQL, modelos de IA",
        it: "Next.js (TypeScript), MySQL, modelli di IA",
        ko: "Next.js (TypeScript), MySQL, AI 모델",
      },
      role: {
        en: "Full Stack Developer",
        es: "Desarrollador Full Stack",
        fr: "Développeur Full Stack",
        de: "Full-Stack-Entwickler",
        zh: "全栈开发工程师",
        ja: "フルスタック開発者",
        ar: "مطور الويب الشامل",
        hi: "फुल स्टैक डेवलपर",
        ru: "Full Stack Разработчик",
        pt: "Desenvolvedor Full Stack",
        it: "Sviluppatore Full Stack",
        ko: "풀스택 개발자",
      },
      contributions: {
        contribution1: {
          en: "Integrated ChatGPT & Perplexity AI for smart health suggestions.",
          es: "Integré ChatGPT y Perplexity AI para sugerencias inteligentes de salud.",
          fr: "Intégré ChatGPT et Perplexity AI pour des suggestions de santé intelligentes.",
          de: "Integration von ChatGPT & Perplexity AI für intelligente Gesundheitsvorschläge.",
          zh: "集成 ChatGPT 和 Perplexity AI 以提供智能健康建议。",
          ja: "ChatGPTとPerplexity AIを統合してスマートな健康提案を実現しました。",
          ar: "دمج ChatGPT و Perplexity AI للحصول على اقتراحات صحية ذكية.",
          hi: "स्मार्ट स्वास्थ्य सुझावों के लिए ChatGPT और Perplexity AI को एकीकृत किया।",
          ru: "Интегрировал ChatGPT и Perplexity AI для умных рекомендаций по здоровью.",
          pt: "Integrei ChatGPT e Perplexity AI para sugestões inteligentes de saúde.",
          it: "Ho integrato ChatGPT e Perplexity AI per suggerimenti sanitari intelligenti.",
          ko: "스마트 건강 제안을 위해 ChatGPT 및 Perplexity AI를 통합했습니다.",
        },
        contribution2: {
          en: "Developed a custom diet planner and health tracking dashboard.",
          es: "Desarrollé un planificador de dietas personalizado y un panel de seguimiento de salud.",
          fr: "Développé un planificateur de régime personnalisé et un tableau de bord de suivi de la santé.",
          de: "Entwickelte einen benutzerdefinierten Ernährungsplaner und ein Gesundheits-Tracking-Dashboard.",
          zh: "开发了自定义饮食计划器和健康跟踪仪表板。",
          ja: "カスタム食事プランナーと健康追跡ダッシュボードを開発しました。",
          ar: "طورت مخطط نظام غذائي مخصص ولوحة معلومات لتتبع الصحة.",
          hi: "एक कस्टम आहार योजनाकार और स्वास्थ्य ट्रैकिंग डैशबोर्ड विकसित किया।",
          ru: "Разработал индивидуальный планировщик диеты и панель мониторинга здоровья.",
          pt: "Desenvolvi um planejador de dieta personalizado e um painel de monitoramento de saúde.",
          it: "Ho sviluppato un pianificatore di dieta personalizzato e un dashboard di monitoraggio della salute.",
          ko: "맞춤형 식단 계획기 및 건강 추적 대시보드를 개발했습니다.",
        },
      },
    },
    druyp: {
      title: {
        en: "Druyp Project - House Renting Platform",
        es: "Proyecto Druyp - Plataforma de Alquiler de Casas",
        fr: "Projet Druyp - Plateforme de Location de Maisons",
        de: "Druyp Projekt - Hausvermietungsplattform",
        zh: "Druyp 项目 - 房屋租赁平台",
        ja: "Druypプロジェクト - 住宅レンタルプラットフォーム",
        ar: "مشروع Druyp - منصة تأجير المنازل",
        hi: "Druyp प्रोजेक्ट - हाउस रेंटिंग प्लेटफॉर्म",
        ru: "Проект Druyp - Платформа аренды жилья",
        pt: "Projeto Druyp - Plataforma de Aluguel de Casas",
        it: "Progetto Druyp - Piattaforma di Affitto Case",
        ko: "Druyp 프로젝트 - 주택 임대 플랫폼",
      },
      overview: {
        en: "A comprehensive platform designed to simplify the house renting process for tenants, homeowners, and service providers.",
        es: "Una plataforma integral diseñada para simplificar el proceso de alquiler de casas para inquilinos, propietarios y proveedores de servicios.",
        fr: "Une plateforme complète conçue pour simplifier le processus de location de maisons pour les locataires, les propriétaires et les prestataires de services.",
        de: "Eine umfassende Plattform, die den Hausvermietungsprozess für Mieter, Hausbesitzer und Dienstleister vereinfacht.",
        zh: "一个全面的平台，旨在简化租户、房主和服务提供商的房屋租赁流程。",
        ja: "テナント、住宅所有者、サービスプロバイダーのための家賃プロセスを簡素化するように設計された包括的なプラットフォーム。",
        ar: "منصة شاملة مصممة لتبسيط عملية استئجار المنازل للمستأجرين وأصحاب المنازل ومقدمي الخدمات.",
        hi: "किरायेदारों, मकान मालिकों और सेवा प्रदाताओं के लिए घर किराए पर लेने की प्रक्रिया को सरल बनाने के लिए डिज़ाइन किया गया एक व्यापक प्लेटफॉर्म।",
        ru: "Комплексная платформа, разработанная для упрощения процесса аренды жилья для арендаторов, домовладельцев и поставщиков услуг.",
        pt: "Uma plataforma abrangente projetada para simplificar o processo de aluguel de casas para inquilinos, proprietários e prestadores de serviços.",
        it: "Una piattaforma completa progettata per semplificare il processo di affitto di case per inquilini, proprietari e fornitori di servizi.",
        ko: "세입자, 주택 소유자 및 서비스 제공업체를 위한 주택 임대 과정을 단순화하도록 설계된 종합 플랫폼입니다.",
      },
      techStack: {
        en: "Node.js, MSSQL with Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        es: "Node.js, MSSQL con Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        fr: "Node.js, MSSQL avec Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        de: "Node.js, MSSQL mit Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        zh: "Node.js, MSSQL with Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        ja: "Node.js, MSSQL with Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        ar: "Node.js, MSSQL with Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        hi: "Node.js, MSSQL with Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        ru: "Node.js, MSSQL with Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        pt: "Node.js, MSSQL with Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        it: "Node.js, MSSQL with Sequelize ORM, Elasticsearch, React.js, Socket.IO",
        ko: "Node.js, MSSQL with Sequelize ORM, Elasticsearch, React.js, Socket.IO",
      },
      role: {
        en: "Full Stack Developer",
        es: "Desarrollador Full Stack",
        fr: "Développeur Full Stack",
        de: "Full-Stack-Entwickler",
        zh: "全栈开发工程师",
        ja: "フルスタック開発者",
        ar: "مطور الويب الشامل",
        hi: "फुल स्टैक डेवलपर",
        ru: "Full Stack Разработчик",
        pt: "Desenvolvedor Full Stack",
        it: "Sviluppatore Full Stack",
        ko: "풀스택 개발자",
      },
      contributions: {
        contribution1: {
          en: "Implemented server-side logic, database management, and advanced search functionalities.",
          es: "Implementé lógica del lado del servidor, gestión de bases de datos y funcionalidades de búsqueda avanzada.",
          fr: "Implémenté la logique côté serveur, la gestion de base de données et les fonctionnalités de recherche avancée.",
          de: "Implementierte serverseitige Logik, Datenbankverwaltung und erweiterte Suchfunktionen.",
          zh: "实现了服务器端逻辑、数据库管理和高级搜索功能。",
          ja: "サーバーサイドロジック、データベース管理、高度な検索機能を実装しました。",
          ar: "نفذت منطق جانب الخادم وإدارة قواعد البيانات ووظائف البحث المتقدمة.",
          hi: "सर्वर-साइड लॉजिक, डेटाबेस प्रबंधन और उन्नत खोज कार्यक्षमताओं को लागू किया।",
          ru: "Реализовал серверную логику, управление базами данных и расширенные функции поиска.",
          pt: "Implementei lógica do lado do servidor, gerenciamento de banco de dados e funcionalidades de pesquisa avançada.",
          it: "Ho implementato logica lato server, gestione del database e funzionalità di ricerca avanzate.",
          ko: "서버 측 로직, 데이터베이스 관리 및 고급 검색 기능을 구현했습니다.",
        },
        contribution2: {
          en: "Played a critical role in developing features that streamlined the rental experience, ensuring high standards of maintenance and user satisfaction.",
          es: "Desempeñé un papel crítico en el desarrollo de características que agilizaron la experiencia de alquiler, garantizando altos estándares de mantenimiento y satisfacción del usuario.",
          fr: "Joué un rôle essentiel dans le développement de fonctionnalités qui ont rationalisé l'expérience de location, assurant des normes élevées de maintenance et de satisfaction des utilisateurs.",
          de: "Spielte eine entscheidende Rolle bei der Entwicklung von Funktionen, die das Mieterlebnis optimierten und hohe Standards für Wartung und Benutzerzufriedenheit sicherstellten.",
          zh: "在开发简化租赁体验的功能方面发挥了关键作用，确保了高标准的维护和用户满意度。",
          ja: "レンタル体験を合理化する機能の開発において重要な役割を果たし、高水準のメンテナンスとユーザー満足度を確保しました。",
          ar: "لعبت دورًا حاسمًا في تطوير الميزات التي بسطت تجربة الإيجار، مما يضمن معايير عالية للصيانة ورضا المستخدم.",
          hi: "किराये के अनुभव को सुव्यवस्थित करने वाली सुविधाओं के विकास में महत्वपूर्ण भूमिका निभाई, जिससे रखरखाव और उपयोगकर्ता संतुष्टि के उच्च मानकों को सुनिश्चित किया गया।",
          ru: "Сыграл ключевую роль в разработке функций, которые упростили процесс аренды, обеспечивая высокие стандарты обслуживания и удовлетворенности пользователей.",
          pt: "Desempenhei um papel crítico no desenvolvimento de recursos que simplificaram a experiência de aluguel, garantindo altos padrões de manutenção e satisfação do usuário.",
          it: "Ho svolto un ruolo critico nello sviluppo di funzionalità che hanno semplificato l'esperienza di affitto, garantendo elevati standard di manutenzione e soddisfazione degli utenti.",
          ko: "임대 경험을 간소화하는 기능을 개발하는 데 중요한 역할을 하여 유지 관리 및 사용자 만족도의 높은 표준을 보장했습니다.",
        },
      },
    },
    tradix: {
      title: {
        en: "Crypto Market Platform - Tradix",
        es: "Plataforma de Mercado Crypto - Tradix",
        fr: "Plateforme de Marché Crypto - Tradix",
        de: "Krypto-Marktplattform - Tradix",
        zh: "加密市场平台 - Tradix",
        ja: "暗号通貨市場プラットフォーム - Tradix",
        ar: "منصة سوق العملات المشفرة - Tradix",
        hi: "क्रिप्टो मार्केट प्लेटफॉर्म - Tradix",
        ru: "Платформа криптовалютного рынка - Tradix",
        pt: "Plataforma de Mercado Cripto - Tradix",
        it: "Piattaforma di Mercato Crypto - Tradix",
        ko: "암호화폐 시장 플랫폼 - Tradix",
      },
      overview: {
        en: "A mobile and web application designed to provide users with real-time insights and tools for crypto trading.",
        es: "Una aplicación móvil y web diseñada para proporcionar a los usuarios información en tiempo real y herramientas para el comercio de criptomonedas.",
        fr: "Une application mobile et web conçue pour fournir aux utilisateurs des informations en temps réel et des outils pour le trading de crypto-monnaies.",
        de: "Eine Mobile- und Web-Anwendung, die Benutzern Echtzeit-Einblicke und Tools für den Krypto-Handel bietet.",
        zh: "一款移动和网络应用程序，旨在为用户提供加密货币交易的实时见解和工具。",
        ja: "ユーザーに暗号通貨取引のためのリアルタイムの洞察とツールを提供するように設計されたモバイルおよびWebアプリケーション。",
        ar: "تطبيق للجوال والويب مصمم لتزويد المستخدمين برؤى وأدوات في الوقت الفعلي لتداول العملات المشفرة.",
        hi: "एक मोबाइल और वेब एप्लिकेशन जो उपयोगकर्ताओं को क्रिप्टो ट्रेडिंग के लिए रीयल-टाइम इनसाइट्स और टूल्स प्रदान करने के लिए डिज़ाइन किया गया है।",
        ru: "Мобильное и веб-приложение, разработанное для предоставления пользователям аналитики в реальном времени и инструментов для торговли криптовалютой.",
        pt: "Um aplicativo móvel e web projetado para fornecer aos usuários insights em tempo real e ferramentas para negociação de criptomoedas.",
        it: "Un'applicazione mobile e web progettata per fornire agli utenti approfondimenti in tempo reale e strumenti per il trading di criptovalute.",
        ko: "사용자에게 암호화폐 거래를 위한 실시간 인사이트와 도구를 제공하도록 설계된 모바일 및 웹 애플리케이션입니다.",
      },
      techStack: {
        en: "React.js for the web platform, React Native for the mobile application, PHP",
        es: "React.js para la plataforma web, React Native para la aplicación móvil, PHP",
        fr: "React.js pour la plateforme web, React Native pour l'application mobile, PHP",
        de: "React.js für die Web-Plattform, React Native für die mobile Anwendung, PHP",
        zh: "React.js 用于网络平台，React Native 用于移动应用程序，PHP",
        ja: "Webプラットフォーム用のReact.js、モバイルアプリケーション用のReact Native、PHP",
        ar: "React.js لمنصة الويب، React Native للتطبيق الجوال، PHP",
        hi: "वेब प्लेटफॉर्म के लिए React.js, मोबाइल एप्लिकेशन के लिए React Native, PHP",
        ru: "React.js для веб-платформы, React Native для мобильного приложения, PHP",
        pt: "React.js para a plataforma web, React Native para o aplicativo móvel, PHP",
        it: "React.js per la piattaforma web, React Native per l'applicazione mobile, PHP",
        ko: "웹 플랫폼용 React.js, 모바일 애플리케이션용 React Native, PHP",
      },
      role: {
        en: "Frontend Developer (React.js), Frontend React Native Developer",
        es: "Desarrollador Frontend (React.js), Desarrollador Frontend React Native",
        fr: "Développeur Frontend (React.js), Développeur Frontend React Native",
        de: "Frontend-Entwickler (React.js), Frontend React Native Entwickler",
        zh: "前端开发工程师 (React.js), 前端 React Native 开发工程师",
        ja: "フロントエンド開発者 (React.js)、フロントエンド React Native 開発者",
        ar: "مطور واجهة أمامية (React.js)، مطور واجهة أمامية React Native",
        hi: "फ्रंटएंड डेवलपर (React.js), फ्रंटएंड React Native डेवलपर",
        ru: "Frontend-разработчик (React.js), Frontend React Native разработчик",
        pt: "Desenvolvedor Frontend (React.js), Desenvolvedor Frontend React Native",
        it: "Sviluppatore Frontend (React.js), Sviluppatore Frontend React Native",
        ko: "프론트엔드 개발자 (React.js), 프론트엔드 React Native 개발자",
      },
      contributions: {
        contribution1: {
          en: "Developed key features for a crypto trading platform, enhancing mobile and web app user engagement through real-time chat, data visualization, and personalized alerts.",
          es: "Desarrollé características clave para una plataforma de comercio de criptomonedas, mejorando la participación de los usuarios de aplicaciones móviles y web a través de chat en tiempo real, visualización de datos y alertas personalizadas.",
          fr: "Développé des fonctionnalités clés pour une plateforme de trading de crypto-monnaies, améliorant l'engagement des utilisateurs d'applications mobiles et web grâce au chat en temps réel, à la visualisation des données et aux alertes personnalisées.",
          de: "Entwickelte Schlüsselfunktionen für eine Krypto-Handelsplattform, verbesserte das Engagement der Benutzer von Mobil- und Web-Apps durch Echtzeit-Chat, Datenvisualisierung und personalisierte Warnungen.",
          zh: "为加密交易平台开发了关键功能，通过实时聊天、数据可视化和个性化提醒增强移动和网络应用程序用户参与度。",
          ja: "暗号通貨取引プラットフォームの主要機能を開発し、リアルタイムチャット、データ可視化、パーソナライズされたアラートを通じてモバイルおよびWebアプリのユーザーエンゲージメントを向上させました。",
          ar: "طورت ميزات رئيسية لمنصة تداول العملات المشفرة، مما عزز مشاركة مستخدمي تطبيقات الجوال والويب من خلال الدردشة في الوقت الفعلي وتصور البيانات والتنبيهات المخصصة.",
          hi: "क्रिप्टो ट्रेडिंग प्लेटफॉर्म के लिए प्रमुख सुविधाएँ विकसित कीं, रीयल-टाइम चैट, डेटा विज़ुअलाइज़ेशन और व्यक्तिगत अलर्ट के माध्यम से मोबाइल और वेब ऐप उपयोगकर्ता जुड़ाव को बढ़ाया।",
          ru: "Разработал ключевые функции для платформы криптовалютной торговли, повысив вовлеченность пользователей мобильных и веб-приложений с помощью чата в реальном времени, визуализации данных и персонализированных оповещений.",
          pt: "Desenvolvi recursos-chave para uma plataforma de negociação de criptomoedas, aprimorando o engajamento do usuário de aplicativos móveis e web por meio de chat em tempo real, visualização de dados e alertas personalizados.",
          it: "Ho sviluppato funzionalità chiave per una piattaforma di trading di criptovalute, migliorando il coinvolgimento degli utenti di app mobili e web attraverso chat in tempo reale, visualizzazione dei dati e avvisi personalizzati.",
          ko: "암호화폐 거래 플랫폼의 주요 기능을 개발하여 실시간 채팅, 데이터 시각화 및 개인화된 알림을 통해 모바일 및 웹 앱 사용자 참여도를 향상시켰습니다.",
        },
        contribution2: {
          en: "Improved UI/UX and integrated advanced trading tools, ensuring a seamless, cohesive user experience across platforms.",
          es: "Mejoré la UI/UX e integré herramientas de comercio avanzadas, asegurando una experiencia de usuario fluida y cohesiva en todas las plataformas.",
          fr: "Amélioré l'UI/UX et intégré des outils de trading avancés, assurant une expérience utilisateur transparente et cohérente sur toutes les plateformes.",
          de: "Verbesserte UI/UX und integrierte fortschrittliche Handelstools, um eine nahtlose, kohärente Benutzererfahrung über alle Plattformen hinweg zu gewährleisten.",
          zh: "改进了UI/UX并集成了高级交易工具，确保跨平台的无缝、连贯的用户体验。",
          ja: "UI/UXを改善し、高度な取引ツールを統合して、プラットフォーム間でシームレスで一貫性のあるユーザーエクスペリエンスを確保しました。",
          ar: "حسنت واجهة المستخدم/تجربة المستخدم ودمجت أدوات تداول متقدمة، مما يضمن تجربة مستخدم سلسة ومتماسكة عبر المنصات.",
          hi: "UI/UX में सुधार किया और उन्नत ट्रेडिंग टूल्स को एकीकृत किया, जिससे प्लेटफॉर्म के बीच एक सहज, सुसंगत उपयोगकर्ता अनुभव सुनिश्चित हुआ।",
          ru: "Улучшил UI/UX и интегрировал продвинутые торговые инструменты, обеспечивая бесперебойный, целостный пользовательский опыт на всех платформах.",
          pt: "Melhorei a UI/UX e integrei ferramentas de negociação avançadas, garantindo uma experiência de usuário perfeita e coesa em todas as plataformas.",
          it: "Ho migliorato l'UI/UX e integrato strumenti di trading avanzati, garantendo un'esperienza utente fluida e coesa su tutte le piattaforme.",
          ko: "UI/UX를 개선하고 고급 거래 도구를 통합하여 플랫폼 전반에 걸쳐 원활하고 일관된 사용자 경험을 보장했습니다.",
        },
      },
    },
    perkTool: {
      title: {
        en: "Perk Tool - Learning Management System",
        es: "Perk Tool - Sistema de Gestión de Aprendizaje",
        fr: "Perk Tool - Système de Gestion d'Apprentissage",
        de: "Perk Tool - Lernmanagementsystem",
        zh: "Perk Tool - 学习管理系统",
        ja: "Perk Tool - 学習管理システム",
        ar: "Perk Tool - نظام إدارة التعلم",
        hi: "Perk Tool - लर्निंग मैनेजमेंट सिस्टम",
        ru: "Perk Tool - Система управления обучением",
        pt: "Perk Tool - Sistema de Gestão de Aprendizagem",
        it: "Perk Tool - Sistema di Gestione dell'Apprendimento",
        ko: "Perk Tool - 학습 관리 시스템",
      },
      overview: {
        en: "Led the creation of an interactive LMS, improving the digital learning environment for students, teachers, and administrators.",
        es: "Lideré la creación de un LMS interactivo, mejorando el entorno de aprendizaje digital para estudiantes, profesores y administradores.",
        fr: "Dirigé la création d'un LMS interactif, améliorant l'environnement d'apprentissage numérique pour les étudiants, les enseignants et les administrateurs.",
        de: "Leitete die Erstellung eines interaktiven LMS, verbesserte die digitale Lernumgebung für Schüler, Lehrer und Administratoren.",
        zh: "领导创建了一个交互式LMS，改善了学生、教师和管理员的数字学习环境。",
        ja: "インタラクティブなLMSの作成を主導し、学生、教師、管理者のためのデジタル学習環境を改善しました。",
        ar: "قاد إنشاء نظام إدارة تعلم تفاعلي، مما حسن بيئة التعلم الرقمية للطلاب والمعلمين والإداريين.",
        hi: "एक इंटरैक्टिव LMS के निर्माण का नेतृत्व किया, जिससे छात्रों, शिक्षकों और प्रशासकों के लिए डिजिटल लर्निंग एनवायरनमेंट में सुधार हुआ।",
        ru: "Руководил созданием интерактивной LMS, улучшая цифровую среду обучения для студентов, преподавателей и администраторов.",
        pt: "Liderei a criação de um LMS interativo, melhorando o ambiente de aprendizagem digital para alunos, professores e administradores.",
        it: "Ho guidato la creazione di un LMS interattivo, migliorando l'ambiente di apprendimento digitale per studenti, insegnanti e amministratori.",
        ko: "상호작용형 LMS 생성을 주도하여 학생, 교사 및 관리자를 위한 디지털 학습 환경을 개선했습니다.",
      },
      techStack: {
        en: "React.js, Ant Design",
        es: "React.js, Ant Design",
        fr: "React.js, Ant Design",
        de: "React.js, Ant Design",
        zh: "React.js, Ant Design",
        ja: "React.js, Ant Design",
        ar: "React.js, Ant Design",
        hi: "React.js, Ant Design",
        ru: "React.js, Ant Design",
        pt: "React.js, Ant Design",
        it: "React.js, Ant Design",
        ko: "React.js, Ant Design",
      },
      role: {
        en: "Frontend Developer",
        es: "Desarrollador Frontend",
        fr: "Développeur Frontend",
        de: "Frontend-Entwickler",
        zh: "前端开发工程师",
        ja: "フロントエンド開発者",
        ar: "مطور واجهة أمامية",
        hi: "फ्रंटएंड डेवलपर",
        ru: "Frontend-разработчик",
        pt: "Desenvolvedor Frontend",
        it: "Sviluppatore Frontend",
        ko: "프론트엔드 개발자",
      },
      contributions: {
        contribution1: {
          en: "Spearheaded frontend development, introducing intuitive UI/UX designs and collaborating with backend teams for feature integration.",
          es: "Encabecé el desarrollo frontend, introduciendo diseños intuitivos de UI/UX y colaborando con equipos de backend para la integración de características.",
          fr: "Dirigé le développement frontend, introduisant des conceptions UI/UX intuitives et collaborant avec les équipes backend pour l'intégration des fonctionnalités.",
          de: "Leitete die Frontend-Entwicklung, führte intuitive UI/UX-Designs ein und arbeitete mit Backend-Teams für die Feature-Integration zusammen.",
          zh: "带领前端开发，引入直观的UI/UX设计，并与后端团队合作进行功能集成。",
          ja: "フロントエンド開発を主導し、直感的なUI/UXデザインを導入し、機能統合のためにバックエンドチームと協力しました。",
          ar: "قاد تطوير الواجهة الأمامية، وقدم تصميمات واجهة مستخدم/تجربة مستخدم بديهية وتعاون مع فرق الواجهة الخلفية لتكامل الميزات.",
          hi: "फ्रंटएंड डेवलपमेंट का नेतृत्व किया, सहज UI/UX डिज़ाइन पेश किए और फीचर इंटीग्रेशन के लिए बैकएंड टीमों के साथ सहयोग किया।",
          ru: "Возглавил разработку фронтенда, внедрил интуитивно понятные дизайны UI/UX и сотрудничал с командами бэкенда для интеграции функций.",
          pt: "Liderou o desenvolvimento frontend, introduzindo designs de UI/UX intuitivos e colaborando com equipes de backend para integração de recursos.",
          it: "Ho guidato lo sviluppo frontend, introducendo design UI/UX intuitivi e collaborando con i team backend per l'integrazione delle funzionalità.",
          ko: "프론트엔드 개발을 주도하여 직관적인 UI/UX 디자인을 도입하고 기능 통합을 위해 백엔드 팀과 협력했습니다.",
        },
      },
    },
  },
  contact: {
    title: {
      en: "Get in Touch",
      es: "Ponte en Contacto",
      fr: "Contactez-moi",
      de: "Kontaktieren Sie mich",
      zh: "联系我",
      ja: "お問い合わせ",
      ar: "تواصل معي",
      hi: "संपर्क करें",
      ru: "Связаться со мной",
      pt: "Entre em Contato",
      it: "Contattami",
      ko: "연락하기",
    },
  },
  chatbot: {
    title: {
      en: "AmitBot 9000",
      es: "AmitBot 9000",
      fr: "AmitBot 9000",
      de: "AmitBot 9000",
      zh: "AmitBot 9000",
      ja: "AmitBot 9000",
      ar: "أميت بوت 9000",
      hi: "अमित बॉट 9000",
      ru: "АмитБот 9000",
      pt: "AmitBot 9000",
      it: "AmitBot 9000",
      ko: "아밋봇 9000",
    },
    voiceAssistant: {
      en: "Voice Assistant",
      es: "Asistente de Voz",
      fr: "Assistant Vocal",
      de: "Sprachassistent",
      zh: "语音助手",
      ja: "音声アシスタント",
      ar: "المساعد الصوتي",
      hi: "आवाज सहायक",
      ru: "Голосовой помощник",
      pt: "Assistente de Voz",
      it: "Assistente Vocale",
      ko: "음성 비서",
    },
    listening: {
      en: "Listening... Speak now",
      es: "Escuchando... Habla ahora",
      fr: "Écoute... Parlez maintenant",
      de: "Höre zu... Sprechen Sie jetzt",
      zh: "正在聆听... 请说话",
      ja: "聞いています... 話してください",
      ar: "جاري الاستماع... تحدث الآن",
      hi: "सुन रहा है... अब बोलें",
      ru: "Слушаю... Говорите сейчас",
      pt: "Ouvindo... Fale agora",
      it: "In ascolto... Parla ora",
      ko: "듣는 중... 지금 말하세요",
    },
    speaking: {
      en: "Speaking...",
      es: "Hablando...",
      fr: "En train de parler...",
      de: "Spreche...",
      zh: "正在说话...",
      ja: "話しています...",
      ar: "يتحدث...",
      hi: "बोल रहा है...",
      ru: "Говорю...",
      pt: "Falando...",
      it: "Parlando...",
      ko: "말하는 중...",
    },
    processing: {
      en: "Processing...",
      es: "Procesando...",
      fr: "Traitement...",
      de: "Verarbeite...",
      zh: "处理中...",
      ja: "処理中...",
      ar: "جاري المعالجة...",
      hi: "प्रोसेसिंग...",
      ru: "Обработка...",
      pt: "Processando...",
      it: "Elaborazione...",
      ko: "처리 중...",
    },
    voiceModeActive: {
      en: "Voice mode active. Tap the microphone to speak.",
      es: "Modo de voz activo. Toca el micrófono para hablar.",
      fr: "Mode vocal actif. Appuyez sur le microphone pour parler.",
      de: "Sprachmodus aktiv. Tippen Sie auf das Mikrofon, um zu sprechen.",
      zh: "语音模式已激活。点击麦克风开始说话。",
      ja: "音声モードがアクティブです。マイクをタップして話してください。",
      ar: "وضع الصوت نشط. انقر على الميكروفون للتحدث.",
      hi: "वॉयस मोड सक्रिय है। बोलने के लिए माइक्रोफोन पर टैप करें।",
      ru: "Голосовой режим активен. Нажмите на микрофон, чтобы говорить.",
      pt: "Modo de voz ativo. Toque no microfone para falar.",
      it: "Modalità vocale attiva. Tocca il microfono per parlare.",
      ko: "음성 모드가 활성화되었습니다. 마이크를 탭하여 말하세요.",
    },
    askAboutAmit: {
      en: "Ask about Amit...",
      es: "Pregunta sobre Amit...",
      fr: "Demandez à propos d'Amit...",
      de: "Fragen Sie über Amit...",
      zh: "询问关于Amit的信息...",
      ja: "Amitについて質問する...",
      ar: "اسأل عن أميت...",
      hi: "अमित के बारे में पूछें...",
      ru: "Спросите об Амите...",
      pt: "Pergunte sobre Amit...",
      it: "Chiedi di Amit...",
      ko: "아밋에 대해 물어보세요...",
    },
    listeningToResponse: {
      en: "Listening to response...",
      es: "Escuchando la respuesta...",
      fr: "Écoute de la réponse...",
      de: "Höre Antwort...",
      zh: "正在听取回应...",
      ja: "応答を聞いています...",
      ar: "الاستماع إلى الرد...",
      hi: "जवाब सुन रहा है...",
      ru: "Слушаю ответ...",
      pt: "Ouvindo a resposta...",
      it: "Ascoltando la risposta...",
      ko: "응답 듣는 중...",
    },
    processingQuestion: {
      en: "Processing your question...",
      es: "Procesando tu pregunta...",
      fr: "Traitement de votre question...",
      de: "Verarbeite Ihre Frage...",
      zh: "正在处理您的问题...",
      ja: "質問を処理しています...",
      ar: "معالجة سؤالك...",
      hi: "आपके प्रश्न को संसाधित कर रहा है...",
      ru: "Обрабатываю ваш вопрос...",
      pt: "Processando sua pergunta...",
      it: "Elaborando la tua domanda...",
      ko: "질문 처리 중...",
    },
    tapMicToSpeak: {
      en: "Tap microphone to speak",
      es: "Toca el micrófono para hablar",
      fr: "Appuyez sur le microphone pour parler",
      de: "Tippen Sie auf das Mikrofon, um zu sprechen",
      zh: "点击麦克风说话",
      ja: "マイクをタップして話す",
      ar: "انقر على الميكروفون للتحدث",
      hi: "माइक्रोफोन पर टैप करके बोलें",
      ru: "Нажмите на микрофон, чтобы говорить",
      pt: "Toque no microfone para falar",
      it: "Tocca il microfono per parlare",
      ko: "마이크를 탭하여 말하세요",
    },
    tryVoiceMode: {
      en: "Try voice mode for a hands-free experience!",
      es: "¡Prueba el modo de voz para una experiencia manos libres!",
      fr: "Essayez le mode vocal pour une expérience mains libres !",
      de: "Probieren Sie den Sprachmodus für ein freihändiges Erlebnis!",
      zh: "尝试语音模式，享受免提体验！",
      ja: "ハンズフリー体験のために音声モードをお試しください！",
      ar: "جرب وضع الصوت للاستمتاع بتجربة بدون استخدام اليدين!",
      hi: "हैंड्स-फ्री अनुभव के लिए वॉयस मोड आज़माएं!",
      ru: "Попробуйте голосовой режим для работы без рук!",
      pt: "Experimente o modo de voz para uma experiência sem as mãos!",
      it: "Prova la modalità vocale per un'esperienza a mani libere!",
      ko: "핸즈프리 경험을 위해 음성 모드를 사용해 보세요!",
    },
    voice: {
      en: "Voice",
      es: "Voz",
      fr: "Voix",
      de: "Stimme",
      zh: "语音",
      ja: "音声",
      ar: "صوت",
      hi: "आवाज़",
      ru: "Голос",
      pt: "Voz",
      it: "Voce",
      ko: "음성",
    },
    language: {
      en: "Language",
      es: "Idioma",
      fr: "Langue",
      de: "Sprache",
      zh: "语言",
      ja: "言語",
      ar: "اللغة",
      hi: "भाषा",
      ru: "Язык",
      pt: "Idioma",
      it: "Lingua",
      ko: "언어",
    },
    settings: {
      en: "Language & Voice Settings",
      es: "Configuración de Idioma y Voz",
      fr: "Paramètres de Langue et de Voix",
      de: "Sprach- und Stimmeinstellungen",
      zh: "语言和语音设置",
      ja: "言語と音声の設定",
      ar: "إعدادات اللغة والصوت",
      hi: "भाषा और आवाज़ सेटिंग्स",
      ru: "Настройки языка и голоса",
      pt: "Configurações de Idioma e Voz",
      it: "Impostazioni di Lingua e Voce",
      ko: "언어 및 음성 설정",
    },
    thinking: {
      en: "AmitBot 9000 is thinking...",
      es: "AmitBot 9000 está pensando...",
      fr: "AmitBot 9000 réfléchit...",
      de: "AmitBot 9000 denkt nach...",
      zh: "AmitBot 9000 正在思考...",
      ja: "AmitBot 9000 は考え中...",
      ar: "أميت بوت 9000 يفكر...",
      hi: "अमित बॉट 9000 सोच रहा है...",
      ru: "АмитБот 9000 думает...",
      pt: "AmitBot 9000 está pensando...",
      it: "AmitBot 9000 sta pensando...",
      ko: "아밋봇 9000이 생각 중...",
    },
    errorMessage: {
      en: "I'm having trouble accessing Amit's information right now. Please try again later.",
      es: "Estoy teniendo problemas para acceder a la información de Amit en este momento. Por favor, inténtalo más tarde.",
      fr: "J'ai du mal à accéder aux informations d'Amit en ce moment. Veuillez réessayer plus tard.",
      de: "Ich habe derzeit Probleme beim Zugriff auf Amits Informationen. Bitte versuchen Sie es später erneut.",
      zh: "我现在无法访问Amit的信息。请稍后再试。",
      ja: "現在、Amitの情報にアクセスできません。後でもう一度お試しください。",
      ar: "أواجه مشكلة في الوصول إلى معلومات أميت الآن. يرجى المحاولة مرة أخرى لاحقًا.",
      hi: "मुझे अभी अमित की जानकारी तक पहुंचने में परेशानी हो रही है। कृपया बाद में पुनः प्रयास करें।",
      ru: "У меня возникли проблемы с доступом к информации Амита прямо сейчас. Пожалуйста, повторите попытку позже.",
      pt: "Estou tendo problemas para acessar as informações do Amit agora. Por favor, tente novamente mais tarde.",
      it: "Sto avendo problemi ad accedere alle informazioni di Amit in questo momento. Si prega di riprovare più tardi.",
      ko: "지금 아밋의 정보에 접근하는 데 문제가 있습니다. 나중에 다시 시도해 주세요.",
    },
  },
  dynamicTexts: {
    askAboutAmit: {
      en: "Ask me about Amit!",
      es: "¡Pregúntame sobre Amit!",
      fr: "Demandez-moi à propos d'Amit !",
      de: "Fragen Sie mich über Amit!",
      zh: "向我询问Amit的信息！",
      ja: "Amitについて質問してください！",
      ar: "اسألني عن أميت!",
      hi: "मुझसे अमित के बारे में पूछें!",
      ru: "Спросите меня об Амите!",
      pt: "Pergunte-me sobre o Amit!",
      it: "Chiedimi di Amit!",
      ko: "아밋에 대해 물어보세요!",
    },
    curiousAboutSkills: {
      en: "Curious about Amit's skills?",
      es: "¿Curioso sobre las habilidades de Amit?",
      fr: "Curieux des compétences d'Amit ?",
      de: "Neugierig auf Amits Fähigkeiten?",
      zh: "想了解Amit的技能？",
      ja: "Amitのスキルについて知りたいですか？",
      ar: "هل أنت فضولي بشأن مهارات أميت؟",
      hi: "अमित के कौशल के बारे में जानना चाहते हैं?",
      ru: "Интересуетесь навыками Амита?",
      pt: "Curioso sobre as habilidades do Amit?",
      it: "Curioso delle competenze di Amit?",
      ko: "아밋의 기술이 궁금하신가요?",
    },
    wantToKnowExperience: {
      en: "Want to know Amit's experience?",
      es: "¿Quieres conocer la experiencia de Amit?",
      fr: "Vous voulez connaître l'expérience d'Amit ?",
      de: "Möchten Sie Amits Erfahrung kennenlernen?",
      zh: "想了解Amit的经验？",
      ja: "Amitの経験について知りたいですか？",
      ar: "هل تريد معرفة خبرة أميت؟",
      hi: "अमित के अनुभव के बारे में जानना चाहते हैं?",
      ru: "Хотите узнать об опыте Амита?",
      pt: "Quer conhecer a experiência do Amit?",
      it: "Vuoi conoscere l'esperienza di Amit?",
      ko: "아밋의 경험을 알고 싶으신가요?",
    },
    discoverProjects: {
      en: "Discover Amit's projects!",
      es: "¡Descubre los proyectos de Amit!",
      fr: "Découvrez les projets d'Amit !",
      de: "Entdecken Sie Amits Projekte!",
      zh: "发现Amit的项目！",
      ja: "Amitのプロジェクトを発見しましょう！",
      ar: "اكتشف مشاريع أميت!",
      hi: "अमित की परियोजनाओं का पता लगाएं!",
      ru: "Откройте для себя проекты Амита!",
      pt: "Descubra os projetos do Amit!",
      it: "Scopri i progetti di Amit!",
      ko: "아밋의 프로젝트를 발견하세요!",
    },
  },
  predefinedQuestions: {
    skills: {
      en: "What are Amit's main skills?",
      es: "¿Cuáles son las principales habilidades de Amit?",
      fr: "Quelles sont les principales compétences d'Amit ?",
      de: "Was sind Amits Hauptfähigkeiten?",
      zh: "Amit的主要技能是什么？",
      ja: "Amitの主なスキルは何ですか？",
      ar: "ما هي المهارات الرئيسية لأميت؟",
      hi: "अमित के मुख्य कौशल क्या हैं?",
      ru: "Какие основные навыки у Амита?",
      pt: "Quais são as principais habilidades do Amit?",
      it: "Quali sono le principali competenze di Amit?",
      ko: "아밋의 주요 기술은 무엇인가요?",
    },
    experience: {
      en: "Tell me about Amit's work experience",
      es: "Háblame sobre la experiencia laboral de Amit",
      fr: "Parlez-moi de l'expérience professionnelle d'Amit",
      de: "Erzählen Sie mir von Amits Berufserfahrung",
      zh: "告诉我Amit的工作经验",
      ja: "Amitの職務経験について教えてください",
      ar: "أخبرني عن خبرة أميت في العمل",
      hi: "मुझे अमित के काम के अनुभव के बारे में बताएं",
      ru: "Расскажите мне об опыте работы Амита",
      pt: "Conte-me sobre a experiência de trabalho do Amit",
      it: "Parlami dell'esperienza lavorativa di Amit",
      ko: "아밋의 직장 경험에 대해 알려주세요",
    },
    projects: {
      en: "What projects has Amit worked on?",
      es: "¿En qué proyectos ha trabajado Amit?",
      fr: "Sur quels projets Amit a-t-il travaillé ?",
      de: "An welchen Projekten hat Amit gearbeitet?",
      zh: "Amit参与过哪些项目？",
      ja: "Amitはどのようなプロジェクトに取り組んできましたか？",
      ar: "ما هي المشاريع التي عمل عليها أميت؟",
      hi: "अमित ने किन परियोजनाओं पर काम किया है?",
      ru: "Над какими проектами работал Амит?",
      pt: "Em quais projetos o Amit trabalhou?",
      it: "Su quali progetti ha lavorato Amit?",
      ko: "아밋이 어떤 프로젝트를 진행했나요?",
    },
    education: {
      en: "What's Amit's educational background?",
      es: "¿Cuál es la formación académica de Amit?",
      fr: "Quelle est la formation d'Amit ?",
      de: "Was ist Amits Bildungshintergrund?",
      zh: "Amit的教育背景是什么？",
      ja: "Amitの学歴は何ですか？",
      ar: "ما هي الخلفية التعليمية لأميت؟",
      hi: "अमित की शैक्षिक पृष्ठभूमि क्या है?",
      ru: "Какое образование у Амита?",
      pt: "Qual é a formação educacional do Amit?",
      it: "Qual è il background educativo di Amit?",
      ko: "아밋의 교육 배경은 무엇인가요?",
    },
    interests: {
      en: "What are Amit's interests?",
      es: "¿Cuáles son los intereses de Amit?",
      fr: "Quels sont les intérêts d'Amit ?",
      de: "Was sind Amits Interessen?",
      zh: "Amit的兴趣是什么？",
      ja: "Amitの興味は何ですか？",
      ar: "ما هي اهتمامات أميت؟",
      hi: "अमित की रुचियां क्या हैं?",
      ru: "Какие интересы у Амита?",
      pt: "Quais são os interesses do Amit?",
      it: "Quali sono gli interessi di Amit?",
      ko: "아밋의 관심사는 무엇인가요?",
    },
  },
}
